### ISSUE TITLE
Add version argument

### ISSUE THREAD

**Issue by dragonxtek** [shramos/polymorph#21]
To know better which version of polymorph is installed, can you add `--version` argument?

I think that with this I have no more things to contribute to your project. It's great and I'll help to massify it
Thank you very much

**Comment by shramos** [comment]
Hi @dragonxtek,

Thank you very much for your comments, they are certainly helping to improve Polymorph.

Regarding the version, the requirement is interesting and I'm writing it down for the next update. I do not consider it a priority at this time because there are other standard mechanisms to know the version of a package of this type, for example using the command `pip3 show polymorph`.
