### ISSUE TITLE
Dissection of specific protocol

### ISSUE THREAD

**Issue by xNi-cOx** [shramos/polymorph#4]
Hello first of all many thanks for the project. It is exactly what I am looking for. I have a question about the dissector. I want to dissect the OPC UA protocol but it is not recognized by tshark. I know that wireshark has a working dissector for that protocol. So tshark should have one too, right?
I also know that my captured packets contain OPC UA messages. Can I define a specific protocol for the dissector? What else can cause this behavior?

Here is a screenshot of my captures packets after the dissect command. As you can the see the opc ua part of the packet ist just RAW.DATA

![image](https://user-images.githubusercontent.com/37293161/46614638-a4d5e380-cb16-11e8-899a-82fedffba022.png)

I'd be happy to get some advice or an inspiration.
Thanks.

**Comment by shramos** [comment]
Hi, I just tried the dissection of the OPC UA protocol with polymorph. I have generated my test environment with the following project: https://github.com/FreeOpcUa/python-opcua

I can confirm that Polymorph is capable of dissecting it:

![opcua capture](https://user-images.githubusercontent.com/15182289/46617881-3a28a600-cb1e-11e8-9799-40cb634a6084.PNG)
![opcua capture2](https://user-images.githubusercontent.com/15182289/46617888-3e54c380-cb1e-11e8-9d10-9d4bc8e2d539.PNG)

As in this case Polymorph will use the Tshark dissectors to dissect this protocol, what happens to you means that Tshark/Wireshark has not been able to dissect it either (you can use the wireshark command from the interface where all the captured templates are found to open them with Wireshark)
Based on my experience with other protocols, this may be due to several factors. The most obvious is that the protocol presents some type of security measure, such as encryption, that prevents the dissectors from interpreting it. The other possibility is a little less obvious, for some protocols the Wireshark dissectors need to capture the beginning of the communication to be able to correctly interpret and dissect the packets, in this way, if Wireshark is capturing when the connection starts, it will correctly interpret the protocol. However, if you put it to capture in the middle of a session, it will not be able to interpret and dissect the packets, this happens, for example, with the windows remote registry protocol. I do not know what your particular casuistry is, but I recommend that you try to put Polymorph to capture before starting the session between the client and the server to check if, in this way, the tool is able to interpret the packets correctly.

**Comment by xNi-cOx** [comment]
Thank you very much for your answer. I was able to dissect the OPC UA protocol. The simulation server i used first seemes to do some encrpytion or signing even when i choosed the endpoint without security. I programmed my own server with the open62541 framework and it works.
